### ISSUE TITLE
how to compile tex file?

### ISSUE THREAD

**Issue by aboobakkar** [mitulsavani/cv#1]
how to compile tex file?

**Comment by mitulsavani** [comment]
Hey @aboobakkar  
I actually haven't compiled my `.tex` file on my system. But I have heard that working with the latex compiler is a really tedious process which you might want to avoid.

If you are planning to work on something like this then I would recommend you to go [here](https://www.sharelatex.com/templates/cv-or-resume/software-developer-resume). Once you click on sharelatex it will take you to _Overleaf_ where you can edit tex file and view the pdf side by side. 

BTW you can also just upload the entire project to your github account from there. Lmk if you have any questions.
